name: bedwars
version: '${project.version}'
main: mrkeith782.bedwars.Bedwars
api-version: 1.19
commands:
  hello:
    description: Says hello.
    usage: /hello
  placearmorstand:
    description: Spawns a armor stand.
    usage: /placearmorstand <id> <string>
  editarmorstand:
    description: Edits an armor stand.
    usage: /editarmorstand <id> <string>
  printarmorstands:
    description: Prints all currently placed armor stands.
    usage: /printarmorstands